// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1rQvRQ8yXvUd_X1H3ZpDxE5XQ7u4lUxs',
    appId: '1:85419467150:ios:0c139328f699ecdac704df',
    messagingSenderId: '85419467150',
    projectId: 'masjid-app-9a7e5',
    storageBucket: 'masjid-app-9a7e5.firebasestorage.app',
    iosBundleId: 'com.example.aqimusSalah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwtMdlFuENdlP3gG-GevXqGfygEInRYZU',
    appId: '1:85419467150:web:f13c073d543ebf4ac704df',
    messagingSenderId: '85419467150',
    projectId: 'masjid-app-9a7e5',
    authDomain: 'masjid-app-9a7e5.firebaseapp.com',
    storageBucket: 'masjid-app-9a7e5.firebasestorage.app',
    measurementId: 'G-Q3B4XK4T8Q',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwtMdlFuENdlP3gG-GevXqGfygEInRYZU',
    appId: '1:85419467150:web:f13c073d543ebf4ac704df',
    messagingSenderId: '85419467150',
    projectId: 'masjid-app-9a7e5',
    authDomain: 'masjid-app-9a7e5.firebaseapp.com',
    storageBucket: 'masjid-app-9a7e5.firebasestorage.app',
    measurementId: 'G-Q3B4XK4T8Q',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1rQvRQ8yXvUd_X1H3ZpDxE5XQ7u4lUxs',
    appId: '1:85419467150:ios:0c139328f699ecdac704df',
    messagingSenderId: '85419467150',
    projectId: 'masjid-app-9a7e5',
    storageBucket: 'masjid-app-9a7e5.firebasestorage.app',
    iosBundleId: 'com.example.aqimusSalah',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBidnfL9jpSOM-xl5BD921XA6i_iUIDuPo',
    appId: '1:85419467150:android:b43f888ab0177539c704df',
    messagingSenderId: '85419467150',
    projectId: 'masjid-app-9a7e5',
    storageBucket: 'masjid-app-9a7e5.firebasestorage.app',
  );

}